//! File-manager "Send to device" context-menu integration.
//!
//! `hfctl filemanager install|update|remove` writes the extension files that
//! put a *Send via Handfast* menu into the file managers shipped with the
//! main Linux desktop environments:
//!
//! | File manager | Desktop     | Mechanism            | User location |
//! |--------------|-------------|----------------------|---------------|
//! | Nautilus     | GNOME       | `nautilus-python`    | `~/.local/share/nautilus-python/extensions/` |
//! | Nemo         | Cinnamon    | `nemo-python`        | `~/.local/share/nemo-python/extensions/` |
//! | Caja         | MATE        | `caja-python`        | `~/.local/share/caja-python/extensions/` |
//! | Dolphin      | KDE Plasma  | KService servicemenu | `~/.local/share/kio/servicemenus/` |
//! | Thunar       | Xfce        | `uca.xml` action     | `~/.config/Thunar/uca.xml` |
//! | PCManFM      | LXDE        | file-manager action  | `~/.local/share/file-manager/actions/` |
//!
//! The GObject extensions (Nautilus/Nemo/Caja) build a *live* per-device
//! submenu by asking `hfctl devices --json`; Dolphin's servicemenu gets
//! static per-device actions regenerated by `filemanager update`, plus an
//! interactive `--pick` fallback. Thunar and PCManFM use the `--pick`
//! picker (their action formats have no dynamic submenus).
//!
//! Everything targets the running `hfctl` binary (resolved via
//! [`std::env::current_exe`]) so the menus keep working across cargo and
//! packaged installs. `--system` installs under `/usr/share` instead.

use std::path::{Path, PathBuf};

use crate::cli::FileManagerAction;
use crate::error::{Error, Result};

/// GObject file managers driven by one shared Python template; only the
/// module name differs.
const GOBJECT_FMS: [(&str, &str); 3] =
    [("nautilus", "Nautilus"), ("nemo", "Nemo"), ("caja", "Caja")];

/// Marker embedded in every generated file so install/remove are idempotent.
const MARKER: &str = "handfast-send";

/// Dispatch `hfctl filemanager …`. `client` is required for `update` (it
/// regenerates per-device Dolphin entries from the live device list).
pub(crate) async fn run(
    action: FileManagerAction,
    client: Option<&handfast_ipc::Client>,
) -> Result<()> {
    match action {
        FileManagerAction::Install { system } => install(system),
        FileManagerAction::Update { system } => {
            let client = client.ok_or_else(|| Error::msg("no daemon connection for update"))?;
            update(client, system).await
        }
        FileManagerAction::Remove { system } => remove(system),
    }
}

/// Absolute path of the running hfctl binary, for Exec lines and the Python
/// extensions (desktop launchers do not always inherit a full PATH).
fn hfctl_bin() -> PathBuf {
    std::env::current_exe().unwrap_or_else(|_| PathBuf::from("hfctl"))
}

/// Install (or refresh) every supported file manager's context menu.
fn install(system: bool) -> Result<()> {
    let mut installed = Vec::new();
    for (fm, module) in GOBJECT_FMS {
        let dir = gobject_dir(fm, system);
        std::fs::create_dir_all(&dir)?;
        let path = dir.join("handfast_send.py");
        write_file_if_changed(&path, &python_extension(module))?;
        installed.push(format!("{fm}: {}", path.display()));
    }

    let dolphin_dir = dolphin_dir(system);
    std::fs::create_dir_all(&dolphin_dir)?;
    let dolphin_path = dolphin_dir.join("handfast-send.desktop");
    write_file_if_changed(&dolphin_path, &dolphin_servicemenu(&[]))?;
    installed.push(format!("dolphin: {}", dolphin_path.display()));

    thunar_merge(system, false)?;
    installed.push(format!("thunar: {}", thunar_path(system).display()));

    let pcmanfm_dir = pcmanfm_dir(system);
    std::fs::create_dir_all(&pcmanfm_dir)?;
    let pcmanfm_path = pcmanfm_dir.join("handfast-send.desktop");
    write_file_if_changed(&pcmanfm_path, &pcmanfm_action())?;
    installed.push(format!("pcmanfm: {}", pcmanfm_path.display()));

    println!("installed Handfast send menus:");
    for line in &installed {
        println!("  {line}");
    }
    if !system {
        println!(
            "\nRestart your file manager (or log out/in) for extensions to load.\n\
             Re-run `hfctl filemanager update` after pairing changes."
        );
    }
    Ok(())
}

/// Regenerate per-device menu entries from the live device list (Dolphin).
async fn update(client: &handfast_ipc::Client, system: bool) -> Result<()> {
    use handfast_ipc::Request;
    let payload = match client.request(Request::DeviceList).await {
        Ok(handfast_ipc::Response::Ok { result }) => result,
        Ok(handfast_ipc::Response::Err { message, .. }) => {
            return Err(Error::msg(format!("daemon: {message}")));
        }
        Err(err) => return Err(Error::msg(format!("ipc: {err}"))),
    };
    let devices: Vec<(String, String)> = payload
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(|row| {
            let id = row.get("id")?.as_str()?.to_string();
            let name = row
                .get("name")
                .and_then(|v| v.as_str())
                .unwrap_or(&id)
                .to_string();
            Some((id, name))
        })
        .collect();

    let dolphin_dir = dolphin_dir(system);
    std::fs::create_dir_all(&dolphin_dir)?;
    let dolphin_path = dolphin_dir.join("handfast-send.desktop");
    write_file_if_changed(&dolphin_path, &dolphin_servicemenu(&devices))?;

    // Refresh the GObject extensions too (they are static templates; cheap).
    for (fm, module) in GOBJECT_FMS {
        let dir = gobject_dir(fm, system);
        std::fs::create_dir_all(&dir)?;
        let path = dir.join("handfast_send.py");
        write_file_if_changed(&path, &python_extension(module))?;
    }

    println!(
        "refreshed file-manager menus ({} device action(s))",
        devices.len()
    );
    Ok(())
}

/// Remove every file this module installs.
fn remove(system: bool) -> Result<()> {
    for (fm, _) in GOBJECT_FMS {
        let path = gobject_dir(fm, system).join("handfast_send.py");
        let _ = std::fs::remove_file(&path);
    }
    let _ = std::fs::remove_file(dolphin_dir(system).join("handfast-send.desktop"));
    let _ = std::fs::remove_file(pcmanfm_dir(system).join("handfast-send.desktop"));
    thunar_merge(system, true)?;
    println!("removed Handfast file-manager menus");
    Ok(())
}

// ---- locations ------------------------------------------------------------

fn gobject_dir(fm: &str, system: bool) -> PathBuf {
    if system {
        PathBuf::from(format!("/usr/share/{fm}-python/extensions"))
    } else {
        home()
            .join(".local/share")
            .join(format!("{fm}-python/extensions"))
    }
}

fn dolphin_dir(system: bool) -> PathBuf {
    if system {
        PathBuf::from("/usr/share/kio/servicemenus")
    } else {
        home().join(".local/share/kio/servicemenus")
    }
}

fn pcmanfm_dir(system: bool) -> PathBuf {
    if system {
        PathBuf::from("/usr/share/file-manager/actions")
    } else {
        home().join(".local/share/file-manager/actions")
    }
}

fn thunar_path(system: bool) -> PathBuf {
    if system {
        PathBuf::from("/etc/xdg/Thunar/uca.xml")
    } else {
        home().join(".config/Thunar/uca.xml")
    }
}

fn home() -> PathBuf {
    std::env::var_os("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("/tmp"))
}

// ---- templates ------------------------------------------------------------

/// One shared Python extension for Nautilus/Nemo/Caja (`module` differs).
fn python_extension(module: &str) -> String {
    let bin = hfctl_bin().display().to_string();
    format!(
        r#"#!/usr/bin/env python3
# Handfast "Send to device" context-menu extension for {module}.
# Generated by `hfctl filemanager install`; re-run to update.
import json
import shutil
import subprocess

import gi

gi.require_version("Gtk", "3.0")
from gi.repository import GObject, Gtk  # noqa: E402
from gi.repository import {module}  # noqa: E402

HFCTL = shutil.which("hfctl") or "{bin}"


def _devices():
    try:
        proc = subprocess.run(
            [HFCTL, "devices", "--json"], capture_output=True, text=True, timeout=5
        )
        rows = json.loads(proc.stdout or "[]")
        return [
            (row.get("id", ""), row.get("name", row.get("id", "?")))
            for row in rows
            if row.get("id")
        ]
    except Exception:
        return []


def _paths(files):
    paths = []
    for f in files:
        loc = f.get_location()
        if loc is None:
            continue
        p = loc.get_path()
        if p:
            paths.append(p)
    return paths


def _send(device_id, paths):
    subprocess.Popen([HFCTL, "send", "-d", device_id] + paths)


class HandfastSendExtension(GObject.GObject, {module}.MenuProvider):
    def __init__(self):
        super().__init__()

    def _build(self, paths):
        submenu = Gtk.Menu()
        devices = _devices()
        if not devices:
            item = Gtk.MenuItem(label="No devices discovered")
            item.set_sensitive(False)
            submenu.append(item)
        else:
            for device_id, name in devices:
                item = Gtk.MenuItem(label=name)
                item.connect("activate", lambda _w, did=device_id: _send(did, paths))
                submenu.append(item)
        submenu.show_all()
        top = {module}.MenuItem(
            name="handfast_send",
            label="Send via Handfast",
            tip="Send to a paired device",
            icon="document-send",
        )
        top.set_submenu(submenu)
        return [top]

    def get_file_items(self, window, files):
        paths = _paths(files)
        return self._build(paths) if paths else []

    def get_background_items(self, window, file):
        return []
"#
    )
}

/// KService servicemenu for Dolphin (and any Konqueror-based popup menu).
/// `devices` become static per-device actions; a `--pick` fallback is always
/// present for devices paired after the last `filemanager update`.
fn dolphin_servicemenu(devices: &[(String, String)]) -> String {
    let bin = hfctl_bin().display().to_string();
    let mut actions = Vec::new();
    let mut action_list = String::new();
    for (id, name) in devices {
        let key = format!("send_to_{id}");
        actions.push(format!(
            "\n[Desktop Action {key}]\nName=Send to {name}\nIcon=document-send\nExec={bin} send -d {id} %F"
        ));
        action_list.push_str(&format!("{key};"));
    }
    action_list.push_str("send_pick;");
    let mut out = String::new();
    out.push_str("[Desktop Entry]\n");
    out.push_str("Type=Service\n");
    out.push_str("ServiceTypes=KonqPopupMenu/Plugin\n");
    out.push_str("MimeType=all/all;\n");
    out.push_str(&format!("Actions={action_list}\n"));
    out.push_str("X-KDE-Priority=TopLevel\n");
    out.push('\n');
    out.push_str(&format!(
        "[Desktop Action send_pick]\nName=Send via Handfast…\nIcon=document-send\nExec={bin} send --pick %F"
    ));
    for action in actions {
        out.push_str(&action);
    }
    out
}

/// PCManFM (and Nautilus-Actions compatible) custom action.
fn pcmanfm_action() -> String {
    let bin = hfctl_bin().display().to_string();
    format!(
        "[Desktop Entry]\nType=Action\nName=Send via Handfast…\nIcon=document-send\nProfiles=profile-zero;\n\n[X-Action-Profile profile-zero]\nMimeTypes=all/all;\nExec={bin} send --pick %F\n"
    )
}

/// Thunar `uca.xml`: merge (or remove) the Handfast action while preserving
/// the user's existing actions. Text-based merge keyed on the unique id.
fn thunar_merge(system: bool, remove: bool) -> Result<()> {
    let path = thunar_path(system);
    if remove {
        if path.exists() {
            let content = std::fs::read_to_string(&path)?;
            let updated = strip_action_block(&content);
            if updated != content {
                std::fs::write(&path, updated)?;
            }
        }
        return Ok(());
    }

    let bin = hfctl_bin().display().to_string();
    let block = format!(
        r#"  <action>
    <icon>document-send</icon>
    <name>Send via Handfast…</name>
    <submenu></submenu>
    <unique-id>{MARKER}</unique-id>
    <command>{bin} send --pick %F</command>
    <description>Send the selected files to a paired device</description>
    <range></range>
    <match>*</match>
    <extensions>*</extensions>
    <directories/>
    <audio-files/>
    <image-files/>
    <text-files/>
    <video-files/>
  </action>
"#
    );

    if !path.exists() {
        std::fs::create_dir_all(path.parent().unwrap_or(Path::new(".")))?;
        let xml =
            format!("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<actions>\n{block}</actions>\n");
        std::fs::write(&path, xml)?;
        return Ok(());
    }

    let content = std::fs::read_to_string(&path)?;
    if content.contains(MARKER) {
        return Ok(()); // already installed
    }
    let updated = content.replace("</actions>", &format!("{block}</actions>"));
    if updated == content {
        return Err(Error::msg(format!(
            "{}: no </actions> closing tag found; refusing to guess",
            path.display()
        )));
    }
    std::fs::write(&path, updated)?;
    Ok(())
}

/// Remove the `<action>` block carrying the Handfast marker.
fn strip_action_block(content: &str) -> String {
    let marker = format!("<unique-id>{MARKER}</unique-id>");
    let Some(marker_pos) = content.find(&marker) else {
        return content.to_string();
    };
    let Some(block_start) = content[..marker_pos].rfind("<action>") else {
        return content.to_string();
    };
    let Some(rel_end) = content[block_start..].find("</action>") else {
        return content.to_string();
    };
    let block_end = block_start + rel_end + "</action>".len();
    let mut out = String::with_capacity(content.len());
    out.push_str(&content[..block_start]);
    out.push_str(&content[block_end..]);
    out
}

/// Write `content` only when it differs (keeps mtimes stable and installs
/// idempotent).
fn write_file_if_changed(path: &Path, content: &str) -> Result<()> {
    match std::fs::read_to_string(path) {
        Ok(existing) if existing == content => return Ok(()),
        _ => {}
    }
    std::fs::write(path, content)?;
    Ok(())
}
