//! File-manager "Send to device" context-menu integration.
//!
//! `hfctl filemanager install|update|remove` writes the extension files that
//! put a *Send via Handfast* menu into the file managers shipped with the
//! main Linux desktop environments:
//!
//! | File manager | Desktop     | Mechanism            | User location |
//! |--------------|-------------|----------------------|---------------|
//! | Nautilus     | GNOME       | `nautilus-python`    | `~/.local/share/nautilus-python/extensions/` |
//! | Nemo         | Cinnamon    | `nemo-python`        | `~/.local/share/nemo-python/extensions/` |
//! | Caja         | MATE        | `caja-python`        | `~/.local/share/caja-python/extensions/` |
//! | Dolphin      | KDE Plasma  | KService servicemenu | `~/.local/share/kio/servicemenus/` |
//! | Thunar       | Xfce        | `uca.xml` action     | `~/.config/Thunar/uca.xml` |
//! | PCManFM      | LXDE        | file-manager action  | `~/.local/share/file-manager/actions/` |
//!
//! The GObject extensions (Nautilus/Nemo/Caja) build a *live* per-device
//! submenu by asking `hfctl devices --json`; Dolphin's servicemenu gets
//! static per-device actions regenerated by `filemanager update`, plus an
//! interactive `--pick` fallback. Thunar and PCManFM use the `--pick`
//! picker (their action formats have no dynamic submenus).
//!
//! Everything targets the running `hfctl` binary (resolved via
//! [`std::env::current_exe`]) so the menus keep working across cargo and
//! packaged installs. `--system` installs under `/usr/share` instead.

use std::path::{Path, PathBuf};

use crate::cli::FileManagerAction;
use crate::error::{Error, Result};

/// GObject file managers driven by one shared Python template; only the
/// module name differs.
const GOBJECT_FMS: [(&str, &str); 3] =
    [("nautilus", "Nautilus"), ("nemo", "Nemo"), ("caja", "Caja")];

/// Marker embedded in every generated file so install/remove are idempotent.
const MARKER: &str = "handfast-send";

/// Dispatch `hfctl filemanager …`. `client` is required for `update` (it
/// regenerates per-device Dolphin entries from the live device list).
pub(crate) async fn run(
    action: FileManagerAction,
    client: Option<&handfast_ipc::Client>,
) -> Result<()> {
    match action {
        FileManagerAction::Install { system } => install(system),
        FileManagerAction::Update { system } => {
            let client = client.ok_or_else(|| Error::msg("no daemon connection for update"))?;
            update(client, system).await
        }
        FileManagerAction::Remove { system } => remove(system),
    }
}

/// Absolute path of the running hfctl binary, for Exec lines and the Python
/// extensions (desktop launchers do not always inherit a full PATH).
fn hfctl_bin() -> PathBuf {
    std::env::current_exe().unwrap_or_else(|_| PathBuf::from("hfctl"))
}

/// Install (or refresh) every supported file manager's context menu.
fn install(system: bool) -> Result<()> {
    let mut installed = Vec::new();
    for (fm, module) in GOBJECT_FMS {
        let dir = gobject_dir(fm, system);
        std::fs::create_dir_all(&dir)?;
        let path = dir.join("handfast_send.py");
        write_file_if_changed(&path, &python_extension(module))?;
        installed.push(format!("{fm}: {}", path.display()));
    }

    let dolphin_dir = dolphin_dir(system);
    std::fs::create_dir_all(&dolphin_dir)?;
    let dolphin_path = dolphin_dir.join("handfast-send.desktop");
    write_file_if_changed(&dolphin_path, &dolphin_servicemenu(&[]))?;
    installed.push(format!("dolphin: {}", dolphin_path.display()));

    if system {
        println!(
            "  thunar: skipped (Thunar reads only ~/.config/Thunar/uca.xml; run without --system)"
        );
    } else {
        thunar_merge(false, false)?;
        installed.push(format!("thunar: {}", thunar_path(false).display()));
    }

    let pcmanfm_dir = pcmanfm_dir(system);
    std::fs::create_dir_all(&pcmanfm_dir)?;
    let pcmanfm_path = pcmanfm_dir.join("handfast-send.desktop");
    write_file_if_changed(&pcmanfm_path, &pcmanfm_action())?;
    installed.push(format!("pcmanfm: {}", pcmanfm_path.display()));

    println!("installed Handfast send menus:");
    for line in &installed {
        println!("  {line}");
    }
    if !system {
        println!(
            "\nRestart your file manager (or log out/in) for extensions to load.\n\
             Re-run `hfctl filemanager update` after pairing changes."
        );
    }
    Ok(())
}

/// Regenerate per-device menu entries from the live device list (Dolphin).
async fn update(client: &handfast_ipc::Client, system: bool) -> Result<()> {
    use handfast_ipc::Request;
    let payload = match client.request(Request::DeviceList).await {
        Ok(handfast_ipc::Response::Ok { result }) => result,
        Ok(handfast_ipc::Response::Err { message, .. }) => {
            return Err(Error::msg(format!("daemon: {message}")));
        }
        Err(err) => return Err(Error::msg(format!("ipc: {err}"))),
    };
    let devices: Vec<(String, String)> = payload
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(|row| {
            // The daemon snapshot keys the device by `device_id`; accept the
            // legacy `id` spelling defensively.
            let id = row
                .get("device_id")
                .or_else(|| row.get("id"))?
                .as_str()?
                .to_string();
            let name = row
                .get("name")
                .and_then(|v| v.as_str())
                .unwrap_or(&id)
                .to_string();
            Some((id, name))
        })
        .collect();

    let dolphin_dir = dolphin_dir(system);
    std::fs::create_dir_all(&dolphin_dir)?;
    let dolphin_path = dolphin_dir.join("handfast-send.desktop");
    write_file_if_changed(&dolphin_path, &dolphin_servicemenu(&devices))?;

    // Refresh the GObject extensions too (they are static templates; cheap).
    for (fm, module) in GOBJECT_FMS {
        let dir = gobject_dir(fm, system);
        std::fs::create_dir_all(&dir)?;
        let path = dir.join("handfast_send.py");
        write_file_if_changed(&path, &python_extension(module))?;
    }

    println!(
        "refreshed file-manager menus ({} device action(s))",
        devices.len()
    );
    Ok(())
}

/// Remove every file this module installs.
fn remove(system: bool) -> Result<()> {
    for (fm, _) in GOBJECT_FMS {
        let path = gobject_dir(fm, system).join("handfast_send.py");
        let _ = std::fs::remove_file(&path);
    }
    let _ = std::fs::remove_file(dolphin_dir(system).join("handfast-send.desktop"));
    let _ = std::fs::remove_file(pcmanfm_dir(system).join("handfast-send.desktop"));
    if !system {
        thunar_merge(false, true)?;
    }
    println!("removed Handfast file-manager menus");
    Ok(())
}

// ---- locations ------------------------------------------------------------

fn gobject_dir(fm: &str, system: bool) -> PathBuf {
    if system {
        PathBuf::from(format!("/usr/share/{fm}-python/extensions"))
    } else {
        home()
            .join(".local/share")
            .join(format!("{fm}-python/extensions"))
    }
}

fn dolphin_dir(system: bool) -> PathBuf {
    if system {
        PathBuf::from("/usr/share/kio/servicemenus")
    } else {
        home().join(".local/share/kio/servicemenus")
    }
}

fn pcmanfm_dir(system: bool) -> PathBuf {
    if system {
        PathBuf::from("/usr/share/file-manager/actions")
    } else {
        home().join(".local/share/file-manager/actions")
    }
}

fn thunar_path(system: bool) -> PathBuf {
    if system {
        PathBuf::from("/etc/xdg/Thunar/uca.xml")
    } else {
        home().join(".config/Thunar/uca.xml")
    }
}

fn home() -> PathBuf {
    std::env::var_os("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("/tmp"))
}

// ---- templates ------------------------------------------------------------

/// One shared Python extension for Nautilus/Nemo/Caja (`module` differs).
/// One shared Python extension for Nautilus/Nemo/Caja (`module` differs).
///
/// Signatures verified against the current upstream docs:
/// - nautilus-python ≥ 4.0 (Nautilus ≥ 43.beta) dropped the `window`
///   parameter: `get_file_items(self, files)`, `get_background_items(self,
///   current_folder)` (GNOME nautilus-python "A Simple Extension").
/// - nemo-python and python-caja still pass the window:
///   `get_file_items(self, window, files)` (Nemo 3.0 MenuProvider /
///   python-caja examples).
fn python_extension(module: &str) -> String {
    let (file_items_sig, background_items_sig) = match module {
        "Nautilus" => ("self, files", "self, current_folder"),
        _ => ("self, window, files", "self, window, current_folder"),
    };
    let bin = hfctl_bin().display().to_string();
    format!(
        r#"#!/usr/bin/env python3
# Handfast "Send to device" context-menu extension for {module}.
# Generated by `hfctl filemanager install`; re-run to update.
import json
import shutil
import subprocess

import gi

gi.require_version("Gtk", "3.0")
from gi.repository import GObject, Gtk  # noqa: E402
from gi.repository import {module}  # noqa: E402

HFCTL = shutil.which("hfctl") or "{bin}"


def _devices():
    try:
        proc = subprocess.run(
            [HFCTL, "devices", "--json"], capture_output=True, text=True, timeout=5
        )
        rows = json.loads(proc.stdout or "[]")
        return [
            (row.get("id", ""), row.get("name", row.get("id", "?")))
            for row in rows
            if row.get("id")
        ]
    except Exception:
        return []


def _paths(files):
    paths = []
    for f in files:
        loc = f.get_location()
        if loc is None:
            continue
        p = loc.get_path()
        if p:
            paths.append(p)
    return paths


def _send(device_id, paths):
    subprocess.Popen([HFCTL, "send", "-d", device_id] + paths)


class HandfastSendExtension(GObject.GObject, {module}.MenuProvider):
    def __init__(self):
        super().__init__()

    def _build(self, paths):
        submenu = Gtk.Menu()
        devices = _devices()
        if not devices:
            item = Gtk.MenuItem(label="No devices discovered")
            item.set_sensitive(False)
            submenu.append(item)
        else:
            for device_id, name in devices:
                item = Gtk.MenuItem(label=name)
                item.connect("activate", lambda _w, did=device_id: _send(did, paths))
                submenu.append(item)
        submenu.show_all()
        top = {module}.MenuItem(
            name="handfast_send",
            label="Send via Handfast",
            tip="Send to a paired device",
            icon="document-send",
        )
        top.set_submenu(submenu)
        return [top]

    def get_file_items({file_items_sig}):
        paths = _paths(files)
        return self._build(paths) if paths else []

    def get_background_items({background_items_sig}):
        return []
"#
    )
}

/// KService servicemenu for Dolphin (and any Konqueror-based popup menu).
/// `devices` become static per-device actions; a `--pick` fallback is always
/// present for devices paired after the last `filemanager update`.
fn dolphin_servicemenu(devices: &[(String, String)]) -> String {
    let bin = hfctl_bin().display().to_string();
    let mut actions = Vec::new();
    let mut action_list = String::new();
    for (id, name) in devices {
        let key = format!("send_to_{id}");
        actions.push(format!(
            "\n[Desktop Action {key}]\nName=Send to {name}\nIcon=document-send\nExec={bin} send -d {id} %F"
        ));
        action_list.push_str(&format!("{key};"));
    }
    action_list.push_str("send_pick;");
    let mut out = String::new();
    out.push_str("[Desktop Entry]\n");
    out.push_str("Type=Service\n");
    out.push_str("ServiceTypes=KonqPopupMenu/Plugin\n");
    out.push_str("MimeType=all/all;\n");
    out.push_str(&format!("Actions={action_list}\n"));
    out.push_str("X-KDE-Priority=TopLevel\n");
    out.push('\n');
    out.push_str(&format!(
        "[Desktop Action send_pick]\nName=Send via Handfast…\nIcon=document-send\nExec={bin} send --pick %F"
    ));
    for action in actions {
        out.push_str(&action);
    }
    out
}

/// PCManFM (and Nautilus-Actions compatible) custom action.
fn pcmanfm_action() -> String {
    let bin = hfctl_bin().display().to_string();
    format!(
        "[Desktop Entry]\nType=Action\nName=Send via Handfast…\nIcon=document-send\nProfiles=profile-zero;\n\n[X-Action-Profile profile-zero]\nMimeTypes=all/all;\nExec={bin} send --pick %F\n"
    )
}

/// Thunar `uca.xml`: merge (or remove) the Handfast action while preserving
/// the user's existing actions. Text-based merge keyed on the unique id.
fn thunar_merge(system: bool, remove: bool) -> Result<()> {
    let path = thunar_path(system);
    if remove {
        if path.exists() {
            let content = std::fs::read_to_string(&path)?;
            let updated = strip_action_block(&content);
            if updated != content {
                std::fs::write(&path, updated)?;
            }
        }
        return Ok(());
    }

    let bin = hfctl_bin().display().to_string();
    // Modern Thunar (docs.xfce.org "Custom Actions"): the action matches by
    // `<patterns>` (glob), not the legacy `<match>`/`<extensions>` fields,
    // and the type toggles are the empty `<directories/>`, `<audio-files/>`,
    // `<image-files/>`, `<text-files/>`, `<video-files/>`, `<other-files/>`
    // elements. `<unique-id>` is how Thunar identifies actions (used by our
    // removal path).
    let block = format!(
        r#"  <action>
    <icon>document-send</icon>
    <name>Send via Handfast…</name>
    <submenu></submenu>
    <unique-id>{MARKER}</unique-id>
    <command>{bin} send --pick %F</command>
    <description>Send the selected files to a paired device</description>
    <patterns>*</patterns>
    <directories/>
    <audio-files/>
    <image-files/>
    <text-files/>
    <video-files/>
    <other-files/>
  </action>
"#
    );

    if !path.exists() {
        std::fs::create_dir_all(path.parent().unwrap_or(Path::new(".")))?;
        let xml =
            format!("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<actions>\n{block}</actions>\n");
        std::fs::write(&path, xml)?;
        return Ok(());
    }

    let content = std::fs::read_to_string(&path)?;
    if content.contains(MARKER) {
        return Ok(()); // already installed
    }
    let updated = content.replace("</actions>", &format!("{block}</actions>"));
    if updated == content {
        return Err(Error::msg(format!(
            "{}: no </actions> closing tag found; refusing to guess",
            path.display()
        )));
    }
    std::fs::write(&path, updated)?;
    Ok(())
}

/// Remove the `<action>` block carrying the Handfast marker.
fn strip_action_block(content: &str) -> String {
    let marker = format!("<unique-id>{MARKER}</unique-id>");
    let Some(marker_pos) = content.find(&marker) else {
        return content.to_string();
    };
    let Some(block_start) = content[..marker_pos].rfind("<action>") else {
        return content.to_string();
    };
    let Some(rel_end) = content[block_start..].find("</action>") else {
        return content.to_string();
    };
    let block_end = block_start + rel_end + "</action>".len();
    let mut out = String::with_capacity(content.len());
    out.push_str(&content[..block_start]);
    out.push_str(&content[block_end..]);
    out
}

/// Write `content` only when it differs (keeps mtimes stable and installs
/// idempotent).
fn write_file_if_changed(path: &Path, content: &str) -> Result<()> {
    match std::fs::read_to_string(path) {
        Ok(existing) if existing == content => return Ok(()),
        _ => {}
    }
    std::fs::write(path, content)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::*;

    #[test]
    fn nautilus_uses_the_modern_signatures() {
        let py = python_extension("Nautilus");
        assert!(py.contains("from gi.repository import Nautilus"));
        // nautilus-python >= 4.0 (Nautilus >= 43.beta) dropped `window`.
        assert!(py.contains("def get_file_items(self, files):"));
        assert!(py.contains("def get_background_items(self, current_folder):"));
        assert!(!py.contains("def get_file_items(self, window, files):"));
    }

    #[test]
    fn nemo_and_caja_keep_the_window_parameter() {
        for module in ["Nemo", "Caja"] {
            let py = python_extension(module);
            assert!(py.contains(&format!("from gi.repository import {module}")));
            assert!(py.contains("def get_file_items(self, window, files):"));
            assert!(py.contains("def get_background_items(self, window, current_folder):"));
        }
    }

    #[test]
    fn dolphin_servicemenu_matches_the_kde_docs() {
        let bin = hfctl_bin().display().to_string();
        let menu = dolphin_servicemenu(&[("abc-123".into(), "Pixel".into())]);
        assert!(menu.contains("Type=Service"));
        assert!(menu.contains("ServiceTypes=KonqPopupMenu/Plugin"));
        assert!(menu.contains("MimeType=all/all;"));
        assert!(menu.contains("X-KDE-Priority=TopLevel"));
        assert!(menu.contains("Actions=send_to_abc-123;send_pick;"));
        assert!(menu.contains(&format!(
            "[Desktop Action send_to_abc-123]\nName=Send to Pixel\nIcon=document-send\nExec={bin} send -d abc-123 %F"
        )));
        assert!(menu.contains(&format!(
            "[Desktop Action send_pick]\nName=Send via Handfast…\nIcon=document-send\nExec={bin} send --pick %F"
        )));
    }

    #[test]
    fn pcmanfm_action_matches_des_ema() {
        let action = pcmanfm_action();
        assert!(action.contains("Type=Action"));
        assert!(action.contains("Profiles=profile-zero;"));
        assert!(action.contains("[X-Action-Profile profile-zero]"));
        assert!(action.contains("MimeTypes=all/all;"));
        assert!(action.contains(&format!("Exec={} send --pick %F", hfctl_bin().display())));
    }

    #[test]
    fn thunar_action_uses_the_modern_patterns_schema() {
        let bin = hfctl_bin().display().to_string();
        let block = format!(
            r#"  <action>
    <icon>document-send</icon>
    <name>Send via Handfast…</name>
    <submenu></submenu>
    <unique-id>{MARKER}</unique-id>
    <command>{bin} send --pick %F</command>
    <description>Send the selected files to a paired device</description>
    <patterns>*</patterns>
    <directories/>
    <audio-files/>
    <image-files/>
    <text-files/>
    <video-files/>
    <other-files/>
  </action>
"#
        );
        assert!(block.contains("<patterns>*</patterns>"));
        assert!(block.contains(&format!("<unique-id>{MARKER}</unique-id>")));
        assert!(!block.contains("<match>") && !block.contains("<extensions>"));
    }

    #[test]
    fn strip_action_block_removes_only_our_action() {
        let foreign = r#"  <action>
    <unique-id>user-1</unique-id>
    <name>User action</name>
  </action>
"#;
        let ours = format!(
            r#"  <action>
    <unique-id>{MARKER}</unique-id>
    <name>Send via Handfast…</name>
  </action>
"#
        );
        let xml = format!("<actions>\n{foreign}{ours}</actions>\n");
        let stripped = strip_action_block(&xml);
        assert!(stripped.contains("user-1"));
        assert!(!stripped.contains(MARKER));
        assert!(stripped.starts_with("<actions>\n"));
        assert!(stripped.ends_with("</actions>\n"));
    }

    #[test]
    fn thunar_merge_is_idempotent_and_removable() {
        static HOME_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
        let _guard = HOME_LOCK.lock().unwrap();

        let dir = std::env::temp_dir().join(format!(
            "hfctl-fm-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        std::env::set_var("HOME", &dir);

        thunar_merge(false, false).unwrap();
        let path = thunar_path(false);
        let once = std::fs::read_to_string(&path).unwrap();
        assert!(once.contains(&format!("<unique-id>{MARKER}</unique-id>")));
        assert!(once.contains("<patterns>*</patterns>"));

        thunar_merge(false, false).unwrap(); // second install must not duplicate
        let twice = std::fs::read_to_string(&path).unwrap();
        assert_eq!(once, twice);

        thunar_merge(false, true).unwrap();
        let removed = std::fs::read_to_string(&path).unwrap();
        assert!(!removed.contains(MARKER));

        let _ = std::fs::remove_dir_all(&dir);
        std::env::remove_var("HOME");
    }
}
